apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: vanilla-hostname
      remoteRef:
        key: "a5783c62-d005-4aef-a636-b2ef0083e7af"
