apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cube-mysql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: "65dec255-4576-43d9-bcf0-b2f000c9af25"
