apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cube-mysql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: "CUBE common MySQL Credentials"
        property: password
