apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-common-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: s3-access-key-id
      remoteRef:
        key: "e0f7592d-680c-45a1-84f8-b2e4012bbf4c"
    - secretKey: s3-secret-access-key
      remoteRef:
        key: "a422d113-bcd9-4508-9f1d-b2e4012be86b"
    - secretKey: whitelist
      remoteRef:
        key: "d8a318c1-961d-4d24-8944-b2e6013487ba"
