apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-common-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: s3-access-key-id
      remoteRef:
        key: "CUBE common s3 Credentials"
        property: accessKey
    - secretKey: s3-secret-access-key
      remoteRef:
        key: "CUBE common s3 Credentials"
        property: secretKey
    - secretKey: whitelist
      remoteRef:
        key: "CUBE common whitelist"
        property: notesPlain
