apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cube-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: "434d1d71-b745-46c4-bdd5-b2f201171152"
