apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cube-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: tunnelToken
      remoteRef:
        key: "Cloudflare CUBE Tunnel Token"
        property: token
