apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-cube-servers
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/CUBE-Region/applications
      targetRevision: main
      path: apps/manifests
      ref: repo
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      targetRevision: 4.26.3
      helm:
        releaseName: minecraft-cube-vanilla
        valueFiles:
          - $repo/apps/values/vanilla.yaml
    - repoURL: https://github.com/chik4ge/minecraft-server-charts
      targetRevision: master
      path: charts/minecraft-proxy
      helm:
        releaseName: minecraft-cube-proxy
        valueFiles:
          - $repo/apps/values/minecraft-proxy.yaml
    - repoURL: https://percona.github.io/percona-helm-charts/
      chart: pxc-db
      targetRevision: 1.17.0
      helm:
        releaseName: cube-pxc-db
        parameters:
          - name: pxc.certManager
            value: "true"
        valuesObject:
          users:
            - name: plan
              host: '%'
              dbs:
                - plan
              passwordSecretRef:
                name: cube-mysql-secret
                key: password
              grants:
                - ALL
                - PRIVILEGES
          haproxy:
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
          pxc:
            resources:
              requests:
                cpu: 100m
          logcollector:
            resources:
              requests:
                cpu: 0
                memory: 0
  destination:
    namespace: minecraft-cube
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.metadata.annotations."kubectl.kubernetes.io/restartedAt"
