apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-cube-servers
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/CUBE-Region/applications
      targetRevision: main
      path: apps/manifests
      ref: repo
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      targetRevision: 4.26.3
      helm:
        releaseName: minecraft-cube-vanilla
        valueFiles:
          - $repo/apps/values/vanilla.yaml
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      targetRevision: 3.9.0
      helm:
        releaseName: minecraft-cube-proxy
        valueFiles:
          - $repo/apps/values/minecraft-proxy.yaml
  destination:
    namespace: minecraft-cube
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
