apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: vanilla-hostname
      remoteRef:
        key: "a5783c62-d005-4aef-a636-b2ef0083e7af"
    - secretKey: velocity-forwarding-secret
      remoteRef:
        key: "716bbdfe-9724-46b3-b790-b2ef00b07645"
    - secretKey: plan-web-address
      remoteRef:
        key: "ae4085d1-5d68-433e-966e-b2f2012b73fb"
