apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-proxy-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: vanilla-hostname
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: vanilla_hostname
    - secretKey: velocity-forwarding-secret
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: velocity_forwarding_secret
    - secretKey: plan-web-address
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: plan_web_address
