apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-cube-vanilla-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: mayastor-3-replica
