apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-cube-vanilla-pvc
  namespace: minecraft-cube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
