apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-vanilla-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: rcon-password
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: rcon_password
    - secretKey: s3-backup-repository
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: s3_backup_repository
    - secretKey: s3-backup-password
      remoteRef:
        key: "CUBE vanilla Credentials"
        property: s3_backup_password
