apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cube-vanilla-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: rcon-password
      remoteRef:
        key: "91305d74-aa58-4b06-9949-b2e401176b80"
    - secretKey: s3-backup-repository
      remoteRef:
        key: "bab3f73d-7fbf-4b81-8dba-b2e4012c89d6"
    - secretKey: s3-backup-password
      remoteRef:
        key: "892d27a2-242f-4e63-896d-b2e4012ca404"
